exclude: "^docs/|/migrations/"
default_stages: [commit]

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-ast
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-docstring-first
      - id: check-case-conflict
      - id: check-merge-conflict
      - id: mixed-line-ending
      - id: detect-private-key
      - id: check-added-large-files
      - id: debug-statements
      - id: check-yaml
      - id: check-toml

  - repo: https://github.com/commitizen-tools/commitizen
    rev: v2.42.0
    hooks:
      - id: commitizen
        stages: [commit-msg]

  - repo: https://github.com/asottile/pyupgrade
    rev: v3.3.1
    hooks:
      - id: pyupgrade
        args: [--py310-plus, --py311-plus]

  - repo: https://github.com/psf/black
    rev: 23.1.0
    hooks:
      - id: black
        args: ["--config=pyproject.toml"]

  - repo: https://github.com/PyCQA/isort
    rev: 5.12.0
    hooks:
      - id: isort
        args: [--settings-path=pyproject.toml]
        additional_dependencies: [toml]

  - repo: https://github.com/PyCQA/flake8
    rev: 6.0.0
    hooks:
      - id: flake8
        args: ["--config=setup.cfg"]
        additional_dependencies: [flake8-isort]

#  - repo: local
#    hooks:
#      - id: check-django-migrations
#        name: Check django migrations
#        entry: python3 manage.py makemigrations --dry-run --check
#        language: system
#        types: [python] # hook only runs if a python file is staged
#        pass_filenames: false

# sets up .pre-commit-ci.yaml to ensure pre-commit dependencies stay up to date
ci:
  autoupdate_schedule: weekly
  skip: []
  submodules: false
