# Generated by Django 4.2.2 on 2023-12-18 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oa_workflow_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='oauserinfo',
            name='name',
            field=models.CharField(blank=True, default='', max_length=480, verbose_name='名称'),
        ),
    ]
