# Generated by Django 4.2.2 on 2023-12-20 17:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('oa_workflow_api', '0002_oauserinfo_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oauserinfo',
            name='staff_code',
            field=models.OneToOneField(db_column='staff_code', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, to_field='username', verbose_name='OA用户工号'),
        ),
    ]
